include "base.conf"
max_epochs: 100
task: regression
wd: 5e-4
data_aug: true
# refer to https://pytorch.org/docs/stable/tensor_attributes.html?highlight=memory_format#torch.torch.memory_format
# highly recommend use 'channels_last' on NVIDIA Tasla A100, V100 and RTX 3090 with typical CNNs
memory_format: "contiguous_format" # select from 'contiguous_format' | 'channels_last' | 'preserve_format'

use_amp: false # if true, it will train in automatic mixed precision mode

data {
    type_: airline
    batch_size: 500
    num_workers: 4
    num_classes: -10
    is_vit: false
}



optimizer {
    type_: CustomSGD
    basic_bs: 500
    lr: 0.1
    momentum: 0.9
    dampening: 0
    weight_decay: ${wd}      # 5e-4
    nesterov: true
}

scheduler {
    type_: CosineAnnealingLR
    T_max: ${max_epochs}
    eta_min: 0
}


criterion {
    type_: CrossEntropyLoss
}